# Generated by Django 4.0.4 on 2022-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_main_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
