# Generated by Django 4.0.4 on 2022-05-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registration',
        ),
    ]
