# Generated by Django 4.0.4 on 2022-05-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='date',
        ),
    ]
