# Generated by Django 4.0.4 on 2022-05-18 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 5, 18, 8, 17, 9, 757985, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
