# Generated by Django 4.0.4 on 2022-05-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created',
            field=models.DateTimeField(default='Asia/Kolkata', editable=False),
        ),
    ]
