# Generated by Django 4.0.4 on 2022-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_registration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(choices=[('ghaziabad', 'ghaziabad'), ('gurgaon', 'gurgaon'), ('karnal', 'karnal'), ('mumbai', 'mumbai'), ('punjab', 'punjab'), ('shimla', 'shimla')], default='shimla', max_length=20, verbose_name='Address'),
        ),
    ]
