# Generated by Django 4.0.4 on 2022-05-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
