# Generated by Django 4.0.4 on 2022-05-23 07:44

from django.db import migrations, models
import pytz


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_registration_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created',
            field=models.DateTimeField(default=pytz.timezone, editable=False),
        ),
    ]
