# Generated by Django 4.0.4 on 2022-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_registration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=20, verbose_name='Address'),
        ),
    ]
