# Generated by Django 4.0.4 on 2022-05-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_registration_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='created',
        ),
    ]
