# Generated by Django 4.0.4 on 2023-06-19 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default=datetime.datetime(2023, 6, 19, 9, 53, 59, 866101, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
