# Generated by Django 4.0.4 on 2023-06-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_registration_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='username',
        ),
    ]
