# Generated by Django 4.0.4 on 2023-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_name_main_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
