# Generated by Django 4.0.4 on 2023-06-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_registration_is_active_registration_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
    ]
