# Generated by Django 4.0.4 on 2023-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_registration_is_active_registration_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Full Name'),
        ),
    ]
