# Generated by Django 4.0.4 on 2023-06-22 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_registration_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
