# Generated by Django 4.0.4 on 2023-06-23 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_registration_options_registration_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. 10 digits allowed.", regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Full Name'),
        ),
    ]
