# Generated by Django 4.0.4 on 2023-06-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
