# Generated by Django 4.0.4 on 2023-06-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_registration_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
