# Generated by Django 4.0.4 on 2023-06-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_registration_passport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
    ]
