# Generated by Django 4.0.4 on 2023-08-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_registration_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
