# Generated by Django 4.0.4 on 2023-06-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_registration_passport_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='passport_photo',
        ),
    ]
